spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/blog
    username: MHIS
    password: MHIS

mybatis:
  configuration:
    map-underscore-to-camel-case: true